### 讀取水利署水庫水情資料

In [72]:
import requests
url ='https://fhyv.wra.gov.tw/FhyWeb/v1/Api/Reservoir/Visual?$format=JSON'
r = requests.get(url)
response = r.text

### 將json讀成data再做成dataframe

In [78]:
import json
import pandas as pd
data = json.loads(response)
df = pd.json_normalize(data,record_path = ['ReservoirRealTimeInfos'])
df

,StationNo,Time,EffectiveStorage,PercentageOfStorage,Status,AccumulatedRainfall,StationName.zh_TW
0,10201,2022-08-16T15:00:00+00:00,16032.282,78.107153,5,0.1,石門水庫
1,10204,2022-08-16T08:00:00+00:00,507.880,50.686627,5,0.0,新山水庫
2,10205,2022-08-16T15:00:00+00:00,22626.360,67.439710,5,0.0,翡翠水庫
3,10405,2022-08-16T15:00:00+00:00,3143.430,99.880846,5,0.8,寶山第二水庫
4,10501,2022-08-16T15:00:00+00:00,2930.552,97.719594,5,0.0,永和山水庫
5,10601,2022-08-16T07:00:00+00:00,888.693,71.366284,5,6.0,明德水庫
6,20101,2022-08-16T15:00:00+00:00,11397.650,98.393949,5,3.4,鯉魚潭水庫
7,20201,2022-08-16T07:00:00+00:00,16321.520,87.552409,5,0.0,德基水庫
8,20501,2022-08-16T07:00:00+00:00,1882.880,51.130482,5,0.0,霧社水庫
9,20502,2022-08-16T07:00:00+00:00,12582.870,97.059865,5,0.0,日月潭水庫
10,20503,2022-08-16T15:00:00+00:00,218.300,43.875869,5,0.3,集集攔河堰
11,20509,2022-08-16T15:00:00+00:00,5107.200,100.000000,5,0.0,湖山水庫
12,30301,2022-08-16T07:00:00+00:00,2472.020,99.499288,5,4.0,仁義潭水庫
13,30401,2022-08-16T08:00:00+00:00,1007.000,77.040777,5,5.7,白河水庫
14,30501,2022-08-16T07:00:00+00:00,5014.000,63.376899,5,1.3,烏山頭水庫
15,30502,2022-08-16T15:00:00+00:00,23816.000,46.738363,5,15.5,曾文水庫
16,30503,2022-08-16T07:00:00+00:00,8940.220,100.000000,5,26.4,南化水庫
17,30802,2022-08-16T15:00:00+00:00,40.000,2.621416,5,23.1,阿公店水庫
18,31201,2022-08-16T15:00:00+00:00,1375.000,51.844339,5,31.2,牡丹水庫

### 讀取Mongo伺服器

In [83]:
import pymongo
client = pymongo.MongoClient('localhost', 27017)

### 選取資料庫

In [84]:
database = client["mongo-sample"]
collection = database["reservoir"]

records = df.to_dict('records') 
collection.insert_many(records)